-- seeds/02_restaurants.sql

INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (1, 'Dennys', '1814 Rockwell Lane', 'Come experience the best in family dining for breakfast, lunch or dinner', 'https://resizer.otstatic.com/v2/photos/xlarge/2/49612964.jpg', 3, 50, 0, 1, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (2, 'Milestones', '1546 Fairmont Avenue', 'Contemporary chain known for their Bellinis, featuring twists on typical bar & grill offerings', 'https://resizer.otstatic.com/v2/photos/xlarge/1/32619050.jpg', 2, 30, 2, 0, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (3, 'The Keg', '1360 Hall Street', 'The Keg Steakhouse & Bar serves the finest cuts of succulent steak, aged for tenderness and grilled to perfection.', 'https://resizer.otstatic.com/v2/photos/xlarge/1/32619051.jpg', 5, 70, 1, 0, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Geranium', '3537 Langtown Road', 'As an Ocean Wise partner, The Boathouse Restaurant is committed to serving only the finest seafood caught sustainably from British Columbia waters', 'https://resizer.otstatic.com/v2/photos/xlarge/1/32619052.jpg', 4, 45, 0, 1, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Central', '2036 Sharon Lane', 'The classics you love prepared with a perfect twist, all served up in an atmosphere that feels just right. That’s the Milestones promise', 'https://resizer.otstatic.com/v2/photos/xlarge/1/32619053.jpg', 4, 70, 0, 1, 2);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Disfrutar', '4597 Sussex Court', 'We, at Tandoori Flame Restaurants, are extremely excited to be bringing our ‘GRAND INDIAN BUFFET’ experience to British Columbia.', 'https://resizer.otstatic.com/v2/photos/xlarge/1/32619054.jpg', 4, 80, 0, 1, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Diverxo', '1941 Stanley Avenue', 'Located just a three-minute walk from the Metrotown Skytrain station, Earls Station Square is an unexpected yet welcoming space to gather for lunch', 'https://resizer.otstatic.com/v2/photos/xlarge/1/32619055.jpg', 3, 55, 0, 1, 1);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Pujol', '2833 Thorn Street', 'Pujol is a globally inspired restaurant focused on using the freshest ingredients and making our food and drinks from scratch.', 'https://resizer.otstatic.com/v2/photos/xlarge/1/32619056.jpg', 4, 75, 1, 0, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Asador Etxebarri', '13 Caldwell Road', 'With a sophisticated dining room, heated beachside patio, vibrant lounge and private event room, each environment offers something unique for guests', 'https://resizer.otstatic.com/v2/photos/xlarge/1/32619057.jpg', 4, 15, 2, 0, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'A Casa do Porco', '2491 Mudlick Road', 'great eats', 'https://resizer.otstatic.com/v2/photos/xlarge/1/32619058.jpg', 4, 65, 1, 0, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Emily’s Tama Hangout', '3734 Caynor Circle', 'When you book a reservation at Haven Kitchen + Bar, seating is standard, and you could be booked on our patio, lounge, or mezzanine.', 'https://resizer.otstatic.com/v2/photos/xlarge/1/31538095.jpg', 4, 45, 0, 0, 1);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Jaxson’s Cat Corner', '1123 Edsel Road', 'Previously known as Guu Garden, our newly rebranded "Eat Bar & Patio Haraheri" is now open once again', 'https://resizer.otstatic.com/v2/photos/xlarge/1/29821694.jpg', 2, 70, 1, 0, 1);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Taylor’s Farm Fresh', '3719 Dog Hill Lane', 'A local favorite and a great place for a night out with that someone special, Little Billys Steakhouse is a family owned and operated restaurant', 'https://resizer.otstatic.com/v2/photos/xlarge/1/32100696.jpg', 3, 100, 0, 1, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Kasey’s Food', '3260 Still Street', 'We are so excited to get an opportunity to re-open and amazing location in the heart of Vancouver and cook some amazing brunches, dinner, burgers and pizza for all', 'https://resizer.otstatic.com/v2/photos/xlarge/1/41692867.jpg', 5, 90, 1, 0, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Ryan’s Place', '18 Breezewood Court', 'Moxies restaurant is a contemporary casual restaurant offering a globally inspired menu and hand crafted cocktails in a vibrant and interactive atmosphere', 'https://resizer.otstatic.com/v2/photos/xlarge/1/42323218.jpg', 3, 90, 1, 0, 1);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Jason’s Ramen', '3093 Armory Road', 'The Restaurant at Delta Golf & Country Club is now taking online reservations', 'https://resizer.otstatic.com/v2/photos/xlarge/1/42732127.jpg', 4, 70, 0, 1, 1);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Kayden’s Coffee', '2562 B Street', 'You’ll love hanging out at Sammy J’s. We know you’ll appreciate the newly designed contemporary interiors', 'https://resizer.otstatic.com/v2/photos/xlarge/1/43416606.jpg', 2, 80, 0, 1, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Sam’s Better Coffee', '2855 Upton Avenue', 'Located in the heart of Yaletown, West Oak is a bustling, modern-rustic space featuring white oak décor and a buzzing open kitchen.', 'https://resizer.otstatic.com/v2/photos/xlarge/2/41701233.jpg', 4, 60, 1, 1, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Quintonil', '2356 Lightning Point Drive', 'When two cultures meet, an exchange occurs, each gaining a new and often better perspective.', 'https://resizer.otstatic.com/v2/photos/xlarge/26011798.jpg', 5, 60, 0, 1, 1);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Septime', '1995 Freedom Lane', 'Simple, fresh, local and handcrafted. Our waterfront Vancouver restaurant, ARC, is the perfect West Coast Setting to enjoy urban artisan food.', 'https://resizer.otstatic.com/v2/photos/xlarge/1/41791858.jpg', 5, 60, 1, 0, 1);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Ray Bean', '4153 Vine Street', 'Tap & Barrel South Surrey is located in The Professional Centre at the juncture of 32nd Avenue and 152nd Street. ', 'https://resizer.otstatic.com/v2/photos/xlarge/2/41701235.jpg', 2, 35,0, 1, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Aldwin’s Street', '4388 Winding Way', 'Historic Surroundings and Modern Fare. Join us today to experience the iconic Brew Pub atmosphere Vancouverites have been enjoying since 1995.', 'https://resizer.otstatic.com/v2/photos/xlarge/1/43531597.jpg', 4, 55, 1, 0, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Matt’s Island', '856 Chapel Street', 'Down the street since 1997. The name’s Original Joe’s.', 'https://resizer.otstatic.com/v2/photos/xlarge/3/41701228.jpg', 2, 50, 0, 1, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Nico’s Jollibee', '248 Bee Avenue', 'We don’t settle for average. Featuring the best craft cocktails, beer, an impressive wine list with a host of signature dishes.', 'https://resizer.otstatic.com/v2/photos/xlarge/1/47109571.jpg', 4, 70, 0, 1, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Kevin’s Cow', '1495 Jennifer Lane', 'Hart House Restaurant is open for lunch, dinner and weekend brunch. Seatings on main floor and 2nd floor to ensure guests safety.', 'https://resizer.otstatic.com/v2/photos/xlarge/1/24929547.jpg', 4, 75, 0, 1, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Alex Stud', '951 Cambridge Drive', 'Pepino’s Spaghetti House, "The House that Spaghetti Built" is an homage to both the cuisine that developed in the Italian immigrant communities', 'https://resizer.otstatic.com/v2/photos/xlarge/2/41745816.jpg', 4, 55, 1, 0, 0);
INSERT INTO restaurants (owner_id, title, address, description, img, review, avg_price, spot2, spot4, spot6) VALUES (4, 'Don Julio', '3619 Poco Mas Drive', 'Classic comfort cooking takes center stage thanks to a fire engine red rotisserie that roasts all manner of proteins. It’s chicken that’s the star here', 'https://resizer.otstatic.com/v2/photos/xlarge/2/41745822.jpg', 4, 90, 0, 0, 2);
